export interface FilterOption {
  value: string
  label: string
  children?: FilterOption[]
}

export interface FilterGroup {
  key: string
  label: string
  options: FilterOption[]
}

export const FILTER_GROUPS: FilterGroup[] = [
  {
    key: 'grade',
    label: 'Grade',
    options: [
      { value: 'elementary', label: 'Elementary', children: [
        { value: 'preschool', label: 'Preschool' },
        { value: 'kindergarten', label: 'Kindergarten' },
        { value: '1st-grade', label: '1st grade' },
        { value: '2nd-grade', label: '2nd grade' },
        { value: '3rd-grade', label: '3rd grade' },
        { value: '4th-grade', label: '4th grade' },
        { value: '5th-grade', label: '5th grade' },
      ]},
      { value: 'middle-school', label: 'Middle school', children: [
        { value: '6th-grade', label: '6th grade' },
        { value: '7th-grade', label: '7th grade' },
        { value: '8th-grade', label: '8th grade' },
      ]},
      { value: 'high-school', label: 'High school', children: [
        { value: '9th-grade', label: '9th grade' },
        { value: '10th-grade', label: '10th grade' },
        { value: '11th-grade', label: '11th grade' },
        { value: '12th-grade', label: '12th grade' },
      ]},
      { value: 'higher-education', label: 'Higher education' },
      { value: 'adult-education', label: 'Adult education' },
      { value: 'not-grade-specific', label: 'Not grade specific' },
    ],
  },
  {
    key: 'subject',
    label: 'Subject',
    options: [
      { value: 'art', label: 'Art', children: [
        { value: 'art-history', label: 'Art history' },
        { value: 'coloring-pages', label: 'Coloring pages' },
        { value: 'graphic-arts', label: 'Graphic arts' },
        { value: 'visual-arts', label: 'Visual arts' },
        { value: 'art-other', label: 'Other (arts)' },
      ]},
      { value: 'english-language-arts', label: 'English language arts', children: [
        { value: 'alphabet', label: 'Alphabet' },
        { value: 'balanced-literacy', label: 'Balanced literacy' },
        { value: 'close-reading', label: 'Close reading' },
        { value: 'creative-writing', label: 'Creative writing' },
        { value: 'ela-test-prep', label: 'ELA test prep' },
        { value: 'grammar', label: 'Grammar' },
        { value: 'handwriting', label: 'Handwriting' },
        { value: 'informational-text', label: 'Informational text' },
        { value: 'library-skills', label: 'Library skills' },
        { value: 'literature', label: 'Literature' },
        { value: 'novel-studies', label: 'Novel studies' },
        { value: 'phonics', label: 'Phonics & phonological awareness' },
        { value: 'poetry', label: 'Poetry' },
        { value: 'reading', label: 'Reading' },
        { value: 'reading-strategies', label: 'Reading strategies' },
        { value: 'science-of-reading', label: 'Science of reading' },
        { value: 'short-stories', label: 'Short stories' },
        { value: 'sight-words', label: 'Sight words' },
        { value: 'spelling', label: 'Spelling' },
        { value: 'vocabulary', label: 'Vocabulary' },
        { value: 'writing', label: 'Writing' },
        { value: 'writing-essays', label: 'Writing-essays' },
        { value: 'writing-expository', label: 'Writing-expository' },
        { value: 'ela-other', label: 'Other (ELA)' },
      ]},
      { value: 'health', label: 'Health' },
      { value: 'math', label: 'Math', children: [
        { value: 'algebra', label: 'Algebra' },
        { value: 'algebra-2', label: 'Algebra 2' },
        { value: 'applied-math', label: 'Applied math' },
        { value: 'arithmetic', label: 'Arithmetic' },
        { value: 'basic-operations', label: 'Basic operations' },
        { value: 'calculus', label: 'Calculus' },
        { value: 'decimals', label: 'Decimals' },
        { value: 'financial-literacy', label: 'Financial literacy' },
        { value: 'fractions', label: 'Fractions' },
        { value: 'geometry', label: 'Geometry' },
        { value: 'graphing', label: 'Graphing' },
        { value: 'math-test-prep', label: 'Math test prep' },
        { value: 'measurement', label: 'Measurement' },
        { value: 'mental-math', label: 'Mental math' },
        { value: 'money-math', label: 'Money math' },
        { value: 'numbers', label: 'Numbers' },
        { value: 'order-of-operations', label: 'Order of operations' },
        { value: 'place-value', label: 'Place value' },
        { value: 'precalculus', label: 'Precalculus' },
        { value: 'statistics', label: 'Statistics' },
        { value: 'telling-time', label: 'Telling time' },
        { value: 'math-other', label: 'Other (math)' },
      ]},
      { value: 'performing-arts', label: 'Performing arts', children: [
        { value: 'dance', label: 'Dance' },
        { value: 'drama', label: 'Drama' },
        { value: 'instrumental-music', label: 'Instrumental music' },
        { value: 'music', label: 'Music' },
        { value: 'music-composition', label: 'Music composition' },
        { value: 'vocal-music', label: 'Vocal music' },
        { value: 'performing-arts-other', label: 'Other (performing arts)' },
      ]},
      { value: 'physical-education', label: 'Physical education' },
      { value: 'science', label: 'Science', children: [
        { value: 'anatomy', label: 'Anatomy' },
        { value: 'archaeology', label: 'Archaeology' },
        { value: 'astronomy', label: 'Astronomy' },
        { value: 'basic-principles', label: 'Basic principles' },
        { value: 'biology', label: 'Biology' },
        { value: 'chemistry', label: 'Chemistry' },
        { value: 'computer-science', label: 'Computer science - technology' },
        { value: 'earth-sciences', label: 'Earth sciences' },
        { value: 'engineering', label: 'Engineering' },
        { value: 'environment', label: 'Environment' },
        { value: 'family-consumer-sciences', label: 'Family consumer sciences' },
        { value: 'forensics', label: 'Forensics' },
        { value: 'general-science', label: 'General science' },
        { value: 'instructional-technology', label: 'Instructional technology' },
        { value: 'marine-science', label: 'Marine science' },
        { value: 'physical-science', label: 'Physical science' },
        { value: 'physics', label: 'Physics' },
        { value: 'robotics', label: 'Robotics' },
        { value: 'science-other', label: 'Other (science)' },
      ]},
      { value: 'social-emotional', label: 'Social emotional', children: [
        { value: 'character-education', label: 'Character education' },
        { value: 'classroom-community', label: 'Classroom community' },
        { value: 'school-counseling', label: 'School counseling' },
        { value: 'school-psychology', label: 'School psychology' },
        { value: 'sel', label: 'Social emotional learning' },
      ]},
      { value: 'social-studies', label: 'Social studies', children: [
        { value: 'aapi-history', label: 'AAPI history' },
        { value: 'african-history', label: 'African history' },
        { value: 'ancient-history', label: 'Ancient history' },
        { value: 'asian-studies', label: 'Asian studies' },
        { value: 'australian-history', label: 'Australian history' },
        { value: 'black-history', label: 'Black history' },
        { value: 'british-history', label: 'British history' },
        { value: 'business', label: 'Business' },
        { value: 'canadian-history', label: 'Canadian history' },
        { value: 'civics', label: 'Civics' },
        { value: 'criminal-justice', label: 'Criminal justice - law' },
        { value: 'economics', label: 'Economics' },
        { value: 'elections-voting', label: 'Elections - voting' },
        { value: 'european-history', label: 'European history' },
        { value: 'geography', label: 'Geography' },
        { value: 'government', label: 'Government' },
        { value: 'latino-hispanic-studies', label: 'Latino and Hispanic studies' },
        { value: 'middle-ages', label: 'Middle Ages' },
        { value: 'native-americans', label: 'Native Americans' },
        { value: 'psychology', label: 'Psychology' },
        { value: 'religion', label: 'Religion' },
        { value: 'us-history', label: 'U.S. history' },
        { value: 'world-history', label: 'World history' },
        { value: 'social-studies-other', label: 'Other (social studies)' },
      ]},
      { value: 'speaking-listening', label: 'Speaking & listening' },
      { value: 'world-languages', label: 'World languages', children: [
        { value: 'asl', label: 'American Sign Language' },
        { value: 'arabic', label: 'Arabic' },
        { value: 'chinese', label: 'Chinese' },
        { value: 'french', label: 'French' },
        { value: 'gaeilge', label: 'Gaeilge' },
        { value: 'german', label: 'German' },
        { value: 'hebrew', label: 'Hebrew' },
        { value: 'italian', label: 'Italian' },
        { value: 'japanese', label: 'Japanese' },
        { value: 'latin', label: 'Latin' },
        { value: 'portuguese', label: 'Portuguese' },
        { value: 'russian', label: 'Russian' },
        { value: 'spanish', label: 'Spanish' },
        { value: 'world-language-other', label: 'Other (world language)' },
      ]},
      { value: 'for-all-subjects', label: 'For all subjects' },
      { value: 'not-subject-specific', label: 'Not subject specific' },
    ],
  },
  {
    key: 'price',
    label: 'Price',
    options: [
      { value: 'free', label: 'Free' },
      { value: 'under-1', label: 'Under $1' },
      { value: '1-3', label: '$1 – $3' },
      { value: '3-5', label: '$3 – $5' },
      { value: '5-10', label: '$5 – $10' },
      { value: '10-plus', label: '$10+' },
    ],
  },
  {
    key: 'format',
    label: 'Format',
    options: [
      { value: 'audio', label: 'Audio' },
      { value: 'digital', label: 'Digital', children: [
        { value: 'boom-cards', label: 'Boom Cards' },
        { value: 'canva', label: 'Canva' },
        { value: 'prezi', label: 'Prezi' },
        { value: 'seesaw', label: 'Seesaw' },
        { value: 'digital-other', label: 'Other (digital)' },
      ]},
      { value: 'easel', label: 'Easel', children: [
        { value: 'easel-activities', label: 'Easel Activities' },
        { value: 'easel-assessments', label: 'Easel Assessments' },
      ]},
      { value: 'ebook', label: 'EBook' },
      { value: 'fonts', label: 'Fonts' },
      { value: 'google-apps', label: 'Google Apps' },
      { value: 'image', label: 'Image' },
      { value: 'interactive-whiteboards', label: 'Interactive whiteboards', children: [
        { value: 'activboard', label: 'Activboard Activities' },
        { value: 'activeinspire', label: 'ActiveInspire Flipchart' },
        { value: 'smart-notebook', label: 'SMART Notebook' },
      ]},
      { value: 'microsoft', label: 'Microsoft', children: [
        { value: 'microsoft-excel', label: 'Microsoft Excel' },
        { value: 'microsoft-onedrive', label: 'Microsoft OneDrive' },
        { value: 'microsoft-powerpoint', label: 'Microsoft PowerPoint' },
        { value: 'microsoft-publisher', label: 'Microsoft Publisher' },
        { value: 'microsoft-word', label: 'Microsoft Word' },
      ]},
      { value: 'pdf', label: 'PDF' },
      { value: 'video', label: 'Video' },
    ],
  },
  {
    key: 'resourceType',
    label: 'Resource type',
    options: [
      { value: 'classroom-decor', label: 'Classroom decor', children: [
        { value: 'bulletin-board', label: 'Bulletin board ideas' },
        { value: 'posters', label: 'Posters' },
        { value: 'word-walls', label: 'Word walls' },
      ]},
      { value: 'forms', label: 'Forms', children: [
        { value: 'classroom-forms', label: 'Classroom forms' },
        { value: 'elective-course-proposals', label: 'Elective course proposals' },
        { value: 'grant-proposals', label: 'Grant proposals' },
        { value: 'professional-documents', label: 'Professional documents' },
        { value: 'school-nurse-documents', label: 'School nurse documents' },
        { value: 'student-council', label: 'Student council' },
        { value: 'teacher-tools', label: 'Teacher tools' },
      ]},
      { value: 'lessons', label: 'Lessons', children: [
        { value: 'awards-certificates', label: 'Awards and certificates' },
        { value: 'classroom-management', label: 'Classroom management' },
        { value: 'homeschool-curricula', label: 'Homeschool curricula' },
        { value: 'leadership-lessons', label: 'Leadership lessons' },
        { value: 'lectures', label: 'Lectures' },
        { value: 'outlines', label: 'Outlines' },
        { value: 'reflective-journals', label: 'Reflective journals for teachers' },
        { value: 'rubrics', label: 'Rubrics' },
        { value: 'syllabi', label: 'Syllabi' },
        { value: 'teacher-manuals', label: 'Teacher manuals' },
        { value: 'teacher-planners', label: 'Teacher planners' },
        { value: 'thematic-unit-plans', label: 'Thematic unit plans' },
        { value: 'tools-common-core', label: 'Tools for common core' },
        { value: 'tools-for-sellers', label: 'Tools for sellers' },
        { value: 'unit-plans', label: 'Unit plans' },
        { value: 'yearlong-curriculum', label: 'Yearlong curriculum' },
      ]},
      { value: 'printables', label: 'Printables' },
      { value: 'clip-art', label: 'Clip art' },
      { value: 'activities', label: 'Activities' },
      { value: 'worksheets', label: 'Worksheets' },
      { value: 'assessments', label: 'Assessments' },
      { value: 'flash-cards', label: 'Flash cards' },
      { value: 'games', label: 'Games' },
      { value: 'graphic-organizers', label: 'Graphic organizers' },
      { value: 'interactive-notebooks', label: 'Interactive notebooks' },
      { value: 'task-cards', label: 'Task cards' },
      { value: 'test-prep', label: 'Test prep' },
    ],
  },
  {
    key: 'standard',
    label: 'Standard',
    options: [
      { value: 'ela-standards', label: 'ELA standards', children: [
        { value: 'ela-k', label: 'Kindergarten' },
        { value: 'ela-1', label: 'Grade 1' },
        { value: 'ela-2', label: 'Grade 2' },
        { value: 'ela-3', label: 'Grade 3' },
        { value: 'ela-4', label: 'Grade 4' },
        { value: 'ela-5', label: 'Grade 5' },
        { value: 'ela-6', label: 'Grade 6' },
        { value: 'ela-7', label: 'Grade 7' },
        { value: 'ela-8', label: 'Grade 8' },
        { value: 'ela-9', label: 'Grade 9' },
        { value: 'ela-10', label: 'Grade 10' },
        { value: 'ela-11', label: 'Grade 11' },
        { value: 'ela-12', label: 'Grade 12' },
      ]},
      { value: 'math-standards', label: 'Math standards', children: [
        { value: 'math-k', label: 'Kindergarten' },
        { value: 'math-1', label: 'Grade 1' },
        { value: 'math-2', label: 'Grade 2' },
        { value: 'math-3', label: 'Grade 3' },
        { value: 'math-4', label: 'Grade 4' },
        { value: 'math-5', label: 'Grade 5' },
        { value: 'math-6', label: 'Grade 6' },
        { value: 'math-7', label: 'Grade 7' },
        { value: 'math-8', label: 'Grade 8' },
        { value: 'math-9', label: 'Grade 9' },
        { value: 'math-10', label: 'Grade 10' },
        { value: 'math-11', label: 'Grade 11' },
        { value: 'math-12', label: 'Grade 12' },
      ]},
    ],
  },
  {
    key: 'theme',
    label: 'Theme',
    options: [
      { value: 'seasonal', label: 'Seasonal', children: [
        { value: 'autumn', label: 'Autumn' },
        { value: 'back-to-school', label: 'Back to school' },
        { value: 'end-of-year', label: 'End of year' },
        { value: 'spring', label: 'Spring' },
        { value: 'summer', label: 'Summer' },
        { value: 'winter', label: 'Winter' },
      ]},
      { value: 'holiday', label: 'Holiday', children: [
        { value: 'aapi-history-month', label: 'AAPI history month' },
        { value: 'april-fools', label: "April Fools' Day" },
        { value: 'arbor-day', label: 'Arbor Day' },
        { value: 'black-history-month', label: 'Black history month' },
        { value: 'christmas-chanukah-kwanzaa', label: 'Christmas-Chanukah-Kwanzaa' },
        { value: 'cinco-de-mayo', label: 'Cinco de Mayo' },
        { value: 'day-of-the-dead', label: 'Day of the Dead / Dia de los Muertos' },
        { value: 'diwali', label: 'Diwali' },
        { value: 'earth-day', label: 'Earth Day' },
        { value: 'easter', label: 'Easter' },
        { value: 'fathers-day', label: "Father's Day" },
        { value: 'groundhog-day', label: 'Groundhog Day' },
        { value: 'halloween', label: 'Halloween' },
        { value: 'hispanic-heritage-month', label: 'Hispanic heritage month' },
        { value: 'july-4', label: 'July 4/Independence Day' },
        { value: 'juneteenth', label: 'Juneteenth' },
        { value: 'labor-day', label: 'Labor Day' },
        { value: 'lunar-new-year', label: 'Lunar New Year' },
        { value: 'mardi-gras', label: 'Mardi Gras' },
        { value: 'mlk-day', label: 'Martin Luther King Day' },
        { value: 'memorial-day', label: 'Memorial Day' },
        { value: 'mothers-day', label: "Mother's Day" },
        { value: 'new-year', label: 'New Year' },
        { value: 'passover', label: 'Passover' },
        { value: 'presidents-day', label: "Presidents' Day" },
        { value: 'ramadan', label: 'Ramadan' },
        { value: 'st-patricks-day', label: "St. Patrick's Day" },
        { value: 'thanksgiving', label: 'Thanksgiving' },
        { value: 'valentines-day', label: "Valentine's Day" },
        { value: 'veterans-day', label: 'Veterans Day' },
        { value: 'womens-history-month', label: "Women's History Month" },
      ]},
    ],
  },
  {
    key: 'audience',
    label: 'Audience',
    options: [
      { value: 'tpt-sellers', label: 'TPT sellers' },
      { value: 'homeschool', label: 'Homeschool' },
      { value: 'parents', label: 'Parents' },
      { value: 'staff-administrators', label: 'Staff & administrators' },
    ],
  },
  {
    key: 'language',
    label: 'Languages',
    options: [
      { value: 'en-espanol', label: 'En español' },
      { value: 'en-francais', label: 'En français' },
      { value: 'english-uk', label: 'English (UK)' },
    ],
  },
  {
    key: 'programs',
    label: 'Programs',
    options: [
      { value: 'programs', label: 'Programs', children: [
        { value: 'ap', label: 'Advanced Placement (AP)' },
        { value: 'early-intervention', label: 'Early intervention' },
        { value: 'gate-gifted', label: 'GATE / Gifted and Talented' },
        { value: 'ib', label: 'International Baccalaureate (IB)' },
        { value: 'montessori', label: 'Montessori' },
      ]},
      { value: 'supports', label: 'Supports', children: [
        { value: 'esl-efl-ell', label: 'ESL, EFL, and ELL' },
        { value: 'special-education', label: 'Special education', children: [
          { value: 'aba', label: 'Applied behavior analysis' },
          { value: 'data', label: 'Data' },
          { value: 'life-skills', label: 'Life skills' },
          { value: 'neurodiversity', label: 'Neurodiversity' },
          { value: 'screenings-assessments', label: 'Screenings and assessments' },
          { value: 'social-skills', label: 'Social skills' },
          { value: 'visual-supports', label: 'Visual supports' },
          { value: 'sped-other', label: 'Other (special education)' },
        ]},
      ]},
      { value: 'specialty', label: 'Specialty', children: [
        { value: 'career-technical-education', label: 'Career and technical education' },
        { value: 'child-care', label: 'Child care' },
        { value: 'coaching', label: 'Coaching' },
        { value: 'cooking', label: 'Cooking' },
        { value: 'leadership', label: 'Leadership' },
        { value: 'occupational-therapy', label: 'Occupational therapy' },
        { value: 'physical-therapy', label: 'Physical therapy' },
        { value: 'professional-development', label: 'Professional development' },
        { value: 'service-learning', label: 'Service learning' },
        { value: 'vocational-education', label: 'Vocational education' },
        { value: 'specialty-other', label: 'Other (specialty)' },
        { value: 'speech-therapy', label: 'Speech therapy', children: [
          { value: 'aac', label: 'AAC' },
          { value: 'fluency-stuttering', label: 'Fluency and stuttering' },
          { value: 'speech-language', label: 'Language' },
          { value: 'speech-articulation', label: 'Speech articulation' },
          { value: 'voice', label: 'Voice' },
          { value: 'speech-other', label: 'Other (speech therapy)' },
        ]},
      ]},
    ],
  },
]

// Map filter values to human-readable search terms
const GRADE_TERMS: Record<string, string> = {
  'preschool': 'preschool',
  'kindergarten': 'kindergarten',
  '1st-grade': '1st grade',
  '2nd-grade': '2nd grade',
  '3rd-grade': '3rd grade',
  '4th-grade': '4th grade',
  '5th-grade': '5th grade',
  '6th-grade': '6th grade',
  '7th-grade': '7th grade',
  '8th-grade': '8th grade',
  '9th-grade': '9th grade',
  '10th-grade': '10th grade',
  '11th-grade': '11th grade',
  '12th-grade': '12th grade',
  'elementary': 'elementary',
  'middle-school': 'middle school',
  'high-school': 'high school',
  'higher-education': 'college',
  'adult-education': 'adult education',
}

const SUBJECT_TERMS: Record<string, string> = {
  'art': 'art',
  'art-history': 'art history',
  'coloring-pages': 'coloring pages',
  'graphic-arts': 'graphic arts',
  'visual-arts': 'visual arts',
  'english-language-arts': 'ELA',
  'alphabet': 'alphabet',
  'balanced-literacy': 'balanced literacy',
  'close-reading': 'close reading',
  'creative-writing': 'creative writing',
  'ela-test-prep': 'ELA test prep',
  'grammar': 'grammar',
  'handwriting': 'handwriting',
  'informational-text': 'informational text',
  'literature': 'literature',
  'novel-studies': 'novel studies',
  'phonics': 'phonics',
  'poetry': 'poetry',
  'reading': 'reading',
  'reading-strategies': 'reading strategies',
  'science-of-reading': 'science of reading',
  'sight-words': 'sight words',
  'spelling': 'spelling',
  'vocabulary': 'vocabulary',
  'writing': 'writing',
  'health': 'health',
  'math': 'math',
  'algebra': 'algebra',
  'algebra-2': 'algebra 2',
  'arithmetic': 'arithmetic',
  'basic-operations': 'basic operations',
  'calculus': 'calculus',
  'decimals': 'decimals',
  'financial-literacy': 'financial literacy',
  'fractions': 'fractions',
  'geometry': 'geometry',
  'graphing': 'graphing',
  'measurement': 'measurement',
  'mental-math': 'mental math',
  'money-math': 'money',
  'numbers': 'numbers',
  'place-value': 'place value',
  'statistics': 'statistics',
  'telling-time': 'telling time',
  'dance': 'dance',
  'drama': 'drama',
  'music': 'music',
  'physical-education': 'physical education',
  'science': 'science',
  'anatomy': 'anatomy',
  'astronomy': 'astronomy',
  'biology': 'biology',
  'chemistry': 'chemistry',
  'computer-science': 'computer science',
  'earth-sciences': 'earth science',
  'engineering': 'engineering',
  'environment': 'environment',
  'general-science': 'science',
  'marine-science': 'marine science',
  'physical-science': 'physical science',
  'physics': 'physics',
  'robotics': 'robotics',
  'character-education': 'character education',
  'sel': 'social emotional learning',
  'social-studies': 'social studies',
  'ancient-history': 'ancient history',
  'black-history': 'black history',
  'civics': 'civics',
  'economics': 'economics',
  'geography': 'geography',
  'government': 'government',
  'us-history': 'US history',
  'world-history': 'world history',
  'speaking-listening': 'speaking and listening',
  'spanish': 'Spanish',
  'french': 'French',
  'asl': 'sign language',
}

const RESOURCE_TERMS: Record<string, string> = {
  'activities': 'activities',
  'worksheets': 'worksheets',
  'assessments': 'assessments',
  'flash-cards': 'flash cards',
  'games': 'games',
  'graphic-organizers': 'graphic organizers',
  'interactive-notebooks': 'interactive notebooks',
  'task-cards': 'task cards',
  'test-prep': 'test prep',
  'printables': 'printables',
  'clip-art': 'clip art',
  'posters': 'posters',
  'rubrics': 'rubrics',
  'unit-plans': 'unit plan',
  'lesson-plans': 'lesson plan',
  'bulletin-board': 'bulletin board',
}

const FORMAT_TERMS: Record<string, string> = {
  'pdf': 'pdf',
  'google-apps': 'google slides',
  'boom-cards': 'boom cards',
  'video': 'video',
  'ebook': 'ebook',
  'microsoft-powerpoint': 'powerpoint',
  'microsoft-word': 'word document',
}

// Build a flat value→label map from all filter groups
function buildLabelMap(): Record<string, string> {
  const map: Record<string, string> = {}
  function walk(opts: FilterOption[]) {
    for (const o of opts) {
      map[o.value] = o.label
      if (o.children) walk(o.children)
    }
  }
  for (const g of FILTER_GROUPS) walk(g.options)
  return map
}
const LABEL_MAP = buildLabelMap()

// Parent-only values that shouldn't appear as search terms
const PARENT_VALUES = new Set([
  'elementary', 'middle-school', 'high-school',
  'english-language-arts', 'math', 'science', 'social-studies',
  'performing-arts', 'art', 'world-languages', 'social-emotional',
  'seasonal', 'holiday', 'programs', 'supports', 'specialty',
])

export function buildQueryFromFilters(selected: Record<string, string[]>, baseKeyword?: string): string {
  // Collect all selected filter terms in display order (grade, subject, resource, format, theme, audience, language, programs)
  const ORDER = ['grade', 'subject', 'resourceType', 'format', 'theme', 'audience', 'language', 'programs']
  const filterTerms: string[] = []

  for (const key of ORDER) {
    const vals = selected[key] || []
    for (const val of vals) {
      if (PARENT_VALUES.has(val)) continue
      // Use known term maps for grade/subject/resource/format, fall back to label map
      let term = ''
      if (key === 'grade') term = GRADE_TERMS[val] || LABEL_MAP[val] || ''
      else if (key === 'subject') term = SUBJECT_TERMS[val] || LABEL_MAP[val] || ''
      else if (key === 'resourceType') term = RESOURCE_TERMS[val] || LABEL_MAP[val] || ''
      else if (key === 'format') term = FORMAT_TERMS[val] || LABEL_MAP[val] || ''
      else term = LABEL_MAP[val] || val.replace(/-/g, ' ')
      if (term) filterTerms.push(term)
    }
  }

  const base = baseKeyword?.trim() || ''
  const allParts = base ? [base, ...filterTerms] : filterTerms
  return allParts.join(' ')
}

export function countSelected(selected: Record<string, string[]>): number {
  return Object.values(selected).reduce((sum, arr) => sum + arr.length, 0)
}
