export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#F1F5F9]">
      <div className="max-w-2xl mx-auto px-8 py-10 space-y-6 text-sm text-gray-700 leading-relaxed">
        <section className="space-y-2">
          <h2 className="text-base font-black text-gray-900">1. Acceptance of Terms</h2>
          <p>By using TeachersBoost, you agree to these Terms & Conditions. If you do not agree, please discontinue use of the service.</p>
        </section>
        <section className="space-y-2">
          <h2 className="text-base font-black text-gray-900">2. Use of Service</h2>
          <p>TeachersBoost provides keyword research, content generation, and market analysis tools for Teachers Pay Teachers sellers. You agree to use the service only for lawful purposes and in accordance with these terms.</p>
        </section>
        <section className="space-y-2">
          <h2 className="text-base font-black text-gray-900">3. Subscriptions & Billing</h2>
          <p>Paid subscriptions are billed monthly. You may cancel at any time, and your access will continue through the end of your current billing period. We do not offer refunds for partial months.</p>
        </section>
        <section className="space-y-2">
          <h2 className="text-base font-black text-gray-900">4. AI-Generated Content</h2>
          <p>Content generated by our AI tools (titles, descriptions, standards) is provided as a starting point. You are responsible for reviewing and verifying all generated content before publishing it to your TpT store. TeachersBoost is not liable for inaccuracies in AI-generated content.</p>
        </section>
        <section className="space-y-2">
          <h2 className="text-base font-black text-gray-900">5. Data Accuracy</h2>
          <p>Keyword competition data is scraped from publicly available TpT search results. We make no guarantees about the accuracy or completeness of this data. Market conditions change and data may not reflect real-time results.</p>
        </section>
        <section className="space-y-2">
          <h2 className="text-base font-black text-gray-900">6. Limitation of Liability</h2>
          <p>TeachersBoost is provided "as is." We are not liable for any indirect, incidental, or consequential damages arising from your use of the service, including lost revenue or TpT store performance.</p>
        </section>
        <section className="space-y-2">
          <h2 className="text-base font-black text-gray-900">7. Account Termination</h2>
          <p>We reserve the right to suspend or terminate accounts that violate these terms or engage in abusive use of the service.</p>
        </section>
        <section className="space-y-2">
          <h2 className="text-base font-black text-gray-900">8. Contact</h2>
          <p>Questions about these terms: <a href="mailto:teachersboost@gmail.com" className="text-gray-800 underline hover:text-rose-600">teachersboost@gmail.com</a></p>
        </section>
      </div>
    </div>
  )
}
